import { StyleSheet, Dimensions } from 'react-native';
import { darkTheme, lightTheme } from '../../styles/theme';

const { width } = Dimensions.get('window');

type AppTheme = typeof lightTheme | typeof darkTheme;

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 55,
    paddingBottom: 15,
    backgroundColor: theme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  headerLogo: {
    width: 100,
    height: 35,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 15,
  },
  iconBadge: {
    backgroundColor: theme.colors.iconSurface,
    padding: 8,
    borderRadius: 12,
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 30,
  },
  profileCard: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 2,
    borderColor: theme.colors.border,
  },
  profileInfo: {
    flex: 1,
    marginLeft: 14,
    justifyContent: 'center',
  },
  name: {
    fontSize: 19,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  handle: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.textSubtitle,
    marginTop: 2,
  },
  bio: {
    fontSize: 13,
    color: theme.colors.textSubtitle,
    marginTop: 8,
    lineHeight: 18,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 8,
  },
  metricCard: {
    flex: 1,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.textStrong,
  },
  metricLabel: {
    fontSize: 12,
    color: theme.colors.textSubtitle,
    marginTop: 4,
  },
  sectionCard: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  goalBlock: {
    marginTop: 12,
  },
  goalTextRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
  },
  goalTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textSubtitle,
  },
  goalValue: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  goalTrack: {
    width: '100%',
    height: 8,
    borderRadius: 99,
    backgroundColor: theme.colors.border,
    overflow: 'hidden',
  },
  goalProgress: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: theme.colors.primary,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.mutedBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 10,
  },
  actionText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textStrong,
  },
  postCard: {
    marginTop: 12,
    backgroundColor: theme.colors.mutedBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  postImage: {
    width: '100%',
    height: 180,
    backgroundColor: theme.colors.lightGray,
  },
  postFooter: {
    padding: 12,
  },
  postCaption: {
    fontSize: 14,
    color: theme.colors.textSubtitle,
    lineHeight: 20,
  },
  postMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  likesText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  commentsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  commentsButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalOverlayPressable: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.32)',
  },
  modalSheet: {
    backgroundColor: theme.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    paddingBottom: 28,
    minHeight: 280,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  commentItem: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.mutedBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  commentUser: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textStrong,
    marginBottom: 4,
  },
  commentText: {
    fontSize: 14,
    color: theme.colors.textSubtitle,
    lineHeight: 19,
  },
});