import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../../styles/theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 55,
    paddingBottom: 15,
    backgroundColor: '#FFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  headerLogo: {
    width: 100,
    height: 35,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 15,
  },
  iconBadge: {
    backgroundColor: '#F0F0F0',
    padding: 8,
    borderRadius: 12,
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 30,
  },
  profileCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 2,
    borderColor: '#EEE',
  },
  profileInfo: {
    flex: 1,
    marginLeft: 14,
    justifyContent: 'center',
  },
  name: {
    fontSize: 19,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  handle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#7A7A7A',
    marginTop: 2,
  },
  bio: {
    fontSize: 13,
    color: '#4E4E4E',
    marginTop: 8,
    lineHeight: 18,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 8,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: '800',
    color: theme.colors.textStrong,
  },
  metricLabel: {
    fontSize: 12,
    color: '#767676',
    marginTop: 4,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  goalBlock: {
    marginTop: 12,
  },
  goalTextRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 7,
  },
  goalTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#444',
  },
  goalValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2D2D2D',
  },
  goalTrack: {
    width: '100%',
    height: 8,
    borderRadius: 99,
    backgroundColor: '#ECECEC',
    overflow: 'hidden',
  },
  goalProgress: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: theme.colors.primary,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAFAFA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 10,
  },
  actionText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textStrong,
  }
});