import { StyleSheet } from 'react-native';
import { darkTheme, lightTheme } from '../../styles/theme';

type AppTheme = typeof lightTheme | typeof darkTheme;

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 55,
      paddingBottom: 15,
      backgroundColor: theme.colors.card,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
    },
    backButton: {
      backgroundColor: theme.colors.iconSurface,
      padding: 8,
      borderRadius: 12,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.colors.textStrong,
    },
    iconBadge: {
      backgroundColor: theme.colors.iconSurface,
      padding: 8,
      borderRadius: 12,
    },
    scrollContent: {
      padding: 14,
      paddingBottom: 30,
    },
    sectionCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: theme.colors.textStrong,
      marginBottom: 4,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.mutedBackground,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 12,
      paddingVertical: 12,
      marginTop: 10,
    },
    optionText: {
      flex: 1,
      marginLeft: 10,
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.textStrong,
    },
    switchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.mutedBackground,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 10,
    },
    switchLabelGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    logoutButton: {
      marginTop: 6,
      backgroundColor: theme.colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    logoutText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '700',
    },
  });
