import { StyleSheet, Dimensions } from 'react-native';
import { darkTheme, lightTheme } from '../../styles/theme';

const { width } = Dimensions.get('window');

type AppTheme = typeof lightTheme | typeof darkTheme;

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 55,
    paddingBottom: 15,
    backgroundColor: theme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  headerLogo: {
    width: 100,
    height: 35,
  },
  headerIcons: {
    flexDirection: 'row',
    gap: 15,
  },
  iconBadge: {
    backgroundColor: theme.colors.iconSurface,
    padding: 8,
    borderRadius: 12,
  },
  storiesBar: {
    paddingVertical: 15,
    backgroundColor: theme.colors.card,
    marginBottom: 8,
  },
  storyBubble: {
    alignItems: 'center',
    marginLeft: 18,
    width: 70,
  },
  storyGradient: {
    width: 66,
    height: 66,
    borderRadius: 33,
    padding: 2.5,
    backgroundColor: theme.colors.primary,
    marginBottom: 6,
  },
  storyInnerBorder: {
    flex: 1,
    backgroundColor: theme.colors.card,
    borderRadius: 30,
    padding: 2,
  },
  storyImg: {
    flex: 1,
    borderRadius: 30,
  },
  storyUsername: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textStrong,
  },
  postCard: {
    backgroundColor: theme.colors.card,
    marginBottom: 12,
    borderRadius: 20,
    marginHorizontal: 10,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  postHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  username: {
    fontWeight: '700',
    fontSize: 15,
    color: theme.colors.textStrong,
  },
  streakBadge: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakText: {
    color: '#000',
    fontWeight: '900',
    fontSize: 13,
    marginTop: -5,
  },
  postImage: {
    width: '100%',
    height: 380,
    backgroundColor: theme.colors.lightGray,
  },
  postFooter: {
    padding: 15,
  },
  interactions: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 12,
  },
  likesCount: {
    fontWeight: '700',
    fontSize: 14,
    color: theme.colors.textStrong,
    marginBottom: 6,
  },
  caption: {
    fontSize: 14,
    color: theme.colors.textSubtitle,
    lineHeight: 20,
  },
  addComment: {
    color: theme.colors.textSubtitle,
    fontSize: 13,
    marginTop: 12,
  },
  commentPreview: {
    marginTop: 8,
    fontSize: 13,
    color: theme.colors.textSubtitle,
    lineHeight: 18,
  },
  commentPreviewUser: {
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalOverlayPressable: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.32)',
  },
  modalSheet: {
    backgroundColor: theme.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    paddingBottom: 28,
    minHeight: 280,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.colors.textStrong,
  },
  commentItem: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.mutedBackground,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  commentUser: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textStrong,
    marginBottom: 4,
  },
  commentText: {
    fontSize: 14,
    color: theme.colors.textSubtitle,
    lineHeight: 19,
  },
  commentStateWrap: {
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentsList: {
    maxHeight: 280,
  },
  commentComposerRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  commentComposerInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 96,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    color: theme.colors.textStrong,
    backgroundColor: theme.colors.background,
  },
  commentSendBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
});